[package]
name = "common"
version = "0.1.0"
authors = ["crow"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
renderer = { path = "../renderer" }

anyhow = "1"
regex = "1.5"
lazy_static = "1.4"
winit = "0.25"